Run tests with docker instead of roswell.
Roswell fails on lots of implementations.
This essentially means that the GitHub actions just always fail, so
they don't function as tests.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,50 +1,83 @@
-name: test
+# This is a basic workflow to help you get started with Actions
 
+name: regression-tests
+
+# Controls when the workflow will run
 on:
+  # Triggers the workflow on push or pull request events but only for the "master" branch
   push:
+    branches: [ "master", "for-shop", "test-repeatability" ]
   pull_request:
-    branches: [ "master" ]
+    branches: [ "master", "for-shop" ]
+
+  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
+  
+
+
+# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
+  # This workflow contains a single job called "test"
   test:
-    name: ${{ matrix.lisp }} on ${{ matrix.os }}
+    # The type of runner that the job will run on
+    runs-on: ubuntu-latest
     strategy:
       matrix:
-        # clisp doesn't run on ubuntu VMs currently
-        lisp: [sbcl-bin,sbcl,ccl,ccl32,ecl,allegro,cmucl,abcl]
-        os: [ubuntu-latest]
-      fail-fast: false
-    runs-on: ${{ matrix.os }}
+        lisp:
+          - sbcl
+          - ccl
+          # - allegro
+          # installation of quicklisp fails on Allegro for some reason. Have to fix this later.
+    container:
+      image: clfoundation/${{ matrix.lisp }}:latest
+    env:
+      I_AGREE_TO_ALLEGRO_EXPRESS_LICENSE: yes
 
+    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-    - uses: actions/checkout@v2
-      
-    - name: cache .roswell
-      id: cache-dot-roswell
-      uses: actions/cache@v1
-      with:
-        path: ~/.roswell
-        key: ${{ runner.os }}-dot-roswell-${{ matrix.lisp }}-${{ hashFiles('**/*.asd') }}
-        restore-keys: |
-          ${{ runner.os }}-dot-roswell-${{ matrix.lisp }}-
-          ${{ runner.os }}-dot-roswell-
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - name: checkout random-state
+        uses: actions/checkout@v3
+        
+      - name: install quicklisp
+        run: install-quicklisp
+        
+      # - name: what is up with Allegro
+      #   run: |
+      #     echo "Github Workspace:"
+      #     ls $GITHUB_WORKSPACE || true
+      #     echo "Quicklisp?"
+      #     ls /github/home
+      #     echo "What's in QL?"
+      #     ls /github/home/quicklisp
 
-    - name: install roswell
-      env:
-       LISP: ${{ matrix.lisp }}
-      run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh -x
+      # - name: Link the project
+      #   run: |
+      #     ln -s $GITHUB_WORKSPACE /github/home/quicklisp/local-projects
+          
+      # - name: What is going on
+      #   run: |
+      #     echo "What's in local-projects?"
+      #     ls /github/home/quicklisp/local-projects
+      #     echo "What's to be loaded?"
+      #     ls $GITHUB_WORKSPACE
 
-    - name: install parachute
-      run: |
-        ros install parachute
-        echo "$HOME/.roswell/bin" >> $GITHUB_PATH
-
-    - name: update ql dist if we have one cached
-      shell: bash
-      run: ros -e "(ql:update-all-dists :prompt nil)"
-
-    - name: load code and run tests
-      shell: bash
-      run: |
-        run-parachute -l "random-state-test" "org.shirakumo.random-state.test"
+      - name: SBCL
+        if: ${{ matrix.lisp == 'sbcl' }}
+        run: sbcl  --non-interactive
+          --load $GITHUB_WORKSPACE/do-test.lisp
+          --eval '(uiop:quit 0)'
+      - name: Allegro
+        if: ${{ matrix.lisp == 'allegro' }}
+        run: alisp -L /github/home/quicklisp/setup.lisp
+          -e "(asdf:load-asd \"$GITHUB_WORKSPACE/random-state.asd\")" 
+          -e '(ql:quickload "random-state/tests")'
+          -e '(asdf:test-system "random-state")'
+          --kill
+      - name: Clozure
+        if: ${{ matrix.lisp == 'ccl' }}
+        run: ccl --batch
+          --load $GITHUB_WORKSPACE/do-test.lisp
+          --eval '(uiop:quit 0)'
+        
